---
abstract: 'XML::Atom extension for OpenSearch data'
author:
  - 'Brian Cassidy <bricas@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Atom-Ext-OpenSearch
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  XML::Atom: 0.28
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
